### ISSUE TITLE
Match the latest spec

### ISSUE THREAD

**Issue by zcorpan** [sindresorhus/srcset#1]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2460%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/srcset/issues/1)

- h descriptor is not allowed anymore
- w and x on the same candidate is not allowed
- Just splitting on commas does not parse correctly (e.g. URLs can contain commas).

http://www.whatwg.org/specs/web-apps/current-work/multipage/embedded-content.html#parse-a-srcset-attribute

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)
### Submitted pull Requests
- [#3 fix issue #1](https://issuehunt.io/r/sindresorhus/srcset/pull/3)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/srcset/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by mahnunchik** [comment]
Hi @zcorpan @sindresorhus 

Do you plan to fix that? Or are there other solutions?

**Comment by zcorpan** [comment]
I do not plan to fix this. For the third point there is a conforming srcset parser impl at https://github.com/baloneysandwiches/parse-srcset/

**Comment by fisker** [comment]
can I work on this

**Comment by evilebottnawi** [comment]
@fisker Do you want to start working at that?

**Comment by fisker** [comment]
@evilebottnawi #3 already started working on this, but have not fix the changes requested for long time.

**Comment by sindresorhus** [comment]
@fisker Go ahead :)

**Comment by fisker** [comment]
After  reading the spec, and I found that `parse-srcset` project [do exactly the spec says](https://github.com/albell/parse-srcset/blob/master/src/parse-srcset.js). I don't think I can do better. So, I'm not going to work on this issue any more, unless we want the similar implementation. I feel I made a mistake [replacing `parse-srcset` with `srcset` on `prettier` project](https://github.com/prettier/prettier/pull/7381).
