### ISSUE TITLE
Image URLs with commas incorrectly parsed

### ISSUE THREAD

**Issue by ryanlward** [sindresorhus/srcset#5]
Probably an edge case for many, but we have image urls with query parameters like:

`https://my.site/image.jpg?foo=bar,baz`

The initial parse call is a string split on `','`, baz gets trimmed off into its own source. 

I'm trying to thing of a way to regex this and if I come up with a solution I'll submit a PR.

**Comment by exentrich** [comment]
Agree. Here another example: `https://i.kinja-img.com/gawker-media/image/upload/c_fill,f_auto,fl_progressive,g_center,h_180,q_80,w_320/rbx48jwtuvpwum29aarr.jpg 320w, https://i.kinja-img.com/gawker-media/image/upload/c_fill,f_auto,fl_progressive,g_center,h_264,q_80,w_470/rbx48jwtuvpwum29aarr.jpg 470w, https://i.kinja-img.com/gawker-media/image/upload/c_fill,f_auto,fl_progressive,g_center,h_80,q_80,w_80/rbx48jwtuvpwum29aarr.jpg 80w `

This happen for images from `gizmodo.com`

**Comment by sindresorhus** [comment]
// @willianveiga

**Comment by molefrog** [comment]
@exentrich @ryanlward Not sure when the PR will be merged, but I made an alternative parser library https://github.com/molefrog/srcset-parse, that does support the latest specs. It probably lacks some of the features of srcset, like generation and runtime checks, but it's generally smaller (in case you care about the bundle size like I do).

Anyways, appreciate if you check it out and thanks @sindresorhus for the inspiration.
