### ISSUE TITLE
[Feature request] Support minified output

### ISSUE THREAD

**Issue by SukkaW** [sindresorhus/srcset#8]
Recently I am implementing "minify srcset" feature for [htmlnano](https://github.com/posthtml/htmlnano), a modular HTML minifier. And I decide to utilize `srcset` in the feature.

According to [HTML Standard](https://html.spec.whatwg.org/#srcset-attributes), both of following HTML markups are valid:

```html
<img srcset="image.png 1x, image2.png 2x, image2.png 3x">
```

```html
<img srcset="image.png 1x,image2.png 2x,image2.png 3x">
```

Currently `srcset`'s `stringify` method only supports the first one. Although I could bring up my own `stringify` function, it is better to have a built-in option for `srcset#stringify`.

**Comment by SukkaW** [comment]
I could bring up a new PR for the issue. But I don't know which API design is better:

```js
# Boolean for the second argument
srcset.stringify(parsed);
srcset.stringify(parsed, true);
srcset.stringify(parsed, false);

# Object for the second argument
srcset.stringify(parsed);
srcset.stringify(parsed, { minify: true });
srcset.stringify(parsed, { minify: false });
```

**Comment by sindresorhus** [comment]
`srcset.stringify(parsed, { minify: true });` looks ok.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/srcset/pull/9#issuecomment-792257416
